DROP TABLE IF EXISTS `stylesheets`;
CREATE TABLE IF NOT EXISTS `stylesheets` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `name` varchar(100) NOT NULL COMMENT 'The name of the stylesheet',
  `description` varchar(255) NOT NULL COMMENT 'The description of the stylesheet',
  `default_background_color` varchar(7) NOT NULL DEFAULT '#fff' COMMENT 'The default background color',
  `default_color` varchar(7) NOT NULL DEFAULT '#000' COMMENT 'The default font color',
  `default_font_size` tinyint(2) unsigned NOT NULL DEFAULT '13' COMMENT 'The default font size',
  `default_line_height` float unsigned NOT NULL DEFAULT '1.231' COMMENT 'The default line height',
  `default_font_family` varchar(100) NOT NULL DEFAULT 'arial,helvetica,clean,sans-serif' COMMENT 'The default font family',
  `default_border_radius` tinyint(2) unsigned NOT NULL DEFAULT '5' COMMENT 'The default border radius size',
  `template_page_width` smallint(5) unsigned NOT NULL DEFAULT '950' COMMENT 'The default page width',
  `template_left_column_width` smallint(5) unsigned NOT NULL DEFAULT '250' COMMENT 'The default right column width',
  `template_right_column_width` smallint(5) unsigned NOT NULL DEFAULT '300' COMMENT 'The default left column width',
  `grid_units` tinyint(3) unsigned NOT NULL DEFAULT '5' COMMENT 'The number of units the stylesheets grid system will support',
  `module_margin` tinyint(2) unsigned NOT NULL DEFAULT '10' COMMENT 'The default margin size used for modules. Inherited by media blocks and some utilities',
  `element_html` text COMMENT 'The html element represents the root of an HTML document.',
  `element_noscript` text COMMENT 'The noscript element represents nothing if scripting is enabled, and represents its children if scripting is disabled. It is used to present different markup to user agents that support scripting and those that don''t support scripting, by affecting how th',
  `element_body` text COMMENT 'The body element represents the main content of the document.',
  `element_section` text COMMENT 'The section element represents a generic section of a document or application. A section, in this context, is a thematic grouping of content, typically with a heading.',
  `element_nav` text COMMENT 'The nav element represents a section of a page that links to other pages or to parts within the page: a section with navigation links.',
  `element_article` text COMMENT 'The article element represents a self-contained composition in a document, page, application, or site and that is, in principle, independently distributable or reusable, e.g. in syndication. This could be a forum post, a magazine or newspaper article, a b',
  `element_aside` text COMMENT 'The aside element represents a section of a page that consists of content that is tangentially related to the content around the aside element, and which could be considered separate from that content. Such sections are often represented as sidebars in pr',
  `element_h1` text COMMENT 'The h1 element represent a heading for a section.',
  `element_h2` text COMMENT 'The h2 element represent a heading for a section.',
  `element_h3` text COMMENT 'The h3 element represent a heading for a section.',
  `element_h4` text COMMENT 'The h4 element represent a heading for a section.',
  `element_h5` text COMMENT 'The h5 element represent a heading for a section.',
  `element_h6` text COMMENT 'The h6 element represent a heading for a section.',
  `element_hgroup` text COMMENT 'The hgroup element represents the heading of a section. The element is used to group a set of h1-h6 elements when the heading has multiple levels, such as subheadings, alternative titles, or taglines.',
  `element_header` text COMMENT 'The header element represents a group of introductory or navigational aids.',
  `element_footer` text COMMENT 'The footer element represents a footer for its nearest ancestor sectioning content or sectioning root element. A footer typically contains information about its section such as who wrote it, links to related documents, copyright data, and the like.',
  `element_address` text COMMENT 'The address element represents the contact information for its nearest article or body element ancestor. If that is the body element, then the contact information applies to the document as a whole.',
  `element_p` text COMMENT 'The p element represents a paragraph.',
  `element_hr` text COMMENT 'The hr element represents a paragraph-level thematic break, e.g. a scene change in a story, or a transition to another topic within a section of a reference book.',
  `element_pre` text COMMENT 'The pre element represents a block of preformatted text, in which structure is represented by typographic conventions rather than by elements.',
  `element_blockquote` text COMMENT 'The blockquote element represents a section that is quoted from another source.',
  `element_ol` text COMMENT 'The ol element represents a list of items, where the items have been intentionally ordered, such that changing the order would change the meaning of the document.',
  `element_ul` text COMMENT 'The ul element represents a list of items, where the order of the items is not important - that is, where changing the order would not materially change the meaning of the document.',
  `element_li` text COMMENT 'The li element represents a list item. If its parent element is an ol, ul, or menu element, then the element is an item of the parent element''s list, as defined for those elements. Otherwise, the list item has no defined list-related relationship to any o',
  `element_dl` text COMMENT 'The dl element represents an association list consisting of zero or more name-value groups (a description list). Each group must consist of one or more names (dt elements) followed by one or more values (dd elements). Within a single dl element, there sho',
  `element_dt` text COMMENT 'The dt element represents the term, or name, part of a term-description group in a description list (dl element).',
  `element_dd` text COMMENT 'The dd element represents the description, definition, or value, part of a term-description group in a description list (dl element).',
  `element_figure` text COMMENT 'The figure element represents some flow content, optionally with a caption, that is self-contained and is typically referenced as a single unit from the main flow of the document.',
  `element_figcaption` text COMMENT 'The figcaption element represents a caption or legend for the rest of the contents of the figcaption element''s parent figure element, if any.',
  `element_div` text COMMENT 'The div element has no special meaning at all. It represents its children. It can be used with the class, lang, and title attributes to mark up semantics common to a group of consecutive elements.',
  `element_a` text COMMENT 'The a element represents a hyperlink (a hypertext anchor).',
  `element_em` text COMMENT 'The em element represents stress emphasis of its contents.',
  `element_strong` text COMMENT 'The strong element represents strong importance for its contents.',
  `element_small` text COMMENT 'The small element represents side comments such as small print.',
  `element_s` text COMMENT 'The s element represents contents that are no longer accurate or no longer relevant.',
  `element_cite` text COMMENT 'The cite element represents the title of a work (e.g. a book, a paper, an essay, a poem, a score, a song, a script, a film, a TV show, a game, a sculpture, a painting, a theatre production, a play, an opera, a musical, an exhibition, a legal case report, ',
  `element_q` text COMMENT 'The q element represents some phrasing content quoted from another source.',
  `element_dfn` text COMMENT 'The dfn element represents the defining instance of a term. The paragraph, description list group, or section that is the nearest ancestor of the dfn element must also contain the definition(s) for the term given by the dfn element.',
  `element_abbr` text COMMENT 'The abbr element represents an abbreviation or acronym, optionally with its expansion. The title attribute may be used to provide an expansion of the abbreviation. The attribute, if specified, must contain an expansion of the abbreviation, and nothing els',
  `element_time` text COMMENT 'The time element represents either a time on a 24 hour clock, or a precise date in the proleptic Gregorian calendar, optionally with a time and a time-zone offset. [GREGORIAN]',
  `element_code` text COMMENT 'The code element represents a fragment of computer code. This could be an XML element name, a filename, a computer program, or any other string that a computer would recognize.',
  `element_var` text COMMENT 'The var element represents a variable. This could be an actual variable in a mathematical expression or programming context, an identifier representing a constant, a function parameter, or just be a term used as a placeholder in prose.',
  `element_samp` text COMMENT 'The samp element represents (sample) output from a program or computing system.',
  `element_kbd` text COMMENT 'The kbd element represents user input (typically keyboard input, although it may also be used to represent other input, such as voice commands).',
  `element_sub` text COMMENT 'The sub element represents a subscript.',
  `element_sup` text COMMENT 'The sup element represents a superscript.',
  `element_i` text COMMENT 'The i element represents a span of text in an alternate voice or mood, or otherwise offset from the normal prose in a manner indicating a different quality of text, such as a taxonomic designation, a technical term, an idiomatic phrase from another langua',
  `element_b` text COMMENT 'The b element represents a span of text to which attention is being drawn for utilitarian purposes without conveying any extra importance and with no implication of an alternate voice or mood, such as key words in a document abstract, product names in a r',
  `element_u` text COMMENT 'The u element represents a span of text with an unarticulated, though explicitly rendered, non-textual annotation, such as labeling the text as being a proper name in Chinese text (a Chinese proper name mark), or labeling the text as being misspelt.',
  `element_mark` text COMMENT 'The mark element represents a run of text in one document marked or highlighted for reference purposes, due to its relevance in another context. When used in a quotation or other block of text referred to from the prose, it indicates a highlight that was ',
  `element_ruby` text COMMENT 'The ruby element allows one or more spans of phrasing content to be marked with ruby annotations. Ruby annotations are short runs of text presented alongside base text, primarily used in East Asian typography as a guide for pronunciation or to include oth',
  `element_rt` text COMMENT 'The rt element marks the ruby text component of a ruby annotation.',
  `element_rp` text COMMENT 'The rp element can be used to provide parentheses around a ruby text component of a ruby annotation, to be shown by user agents that don''t support ruby annotations.',
  `element_bdi` text COMMENT 'The bdi element represents a span of text that is to be isolated from its surroundings for the purposes of bidirectional text formatting. [BIDI]',
  `element_bdo` text COMMENT 'The bdo element represents explicit text directionality formatting control for its children. It allows authors to override the Unicode bidirectional algorithm by explicitly specifying a direction override. [BIDI]',
  `element_span` text COMMENT 'The span element doesn''t mean anything on its own, but can be useful when used together with the global attributes, e.g. class, lang, or dir. It represents its children.',
  `element_br` text COMMENT 'The br element represents a line break.',
  `element_wbr` text COMMENT 'The wbr element represents a line break opportunity.',
  `element_ins` text COMMENT 'The ins element represents an addition to the document.',
  `element_del` text COMMENT 'The del element represents a removal from the document.',
  `element_img` text COMMENT 'The img element represents an image.',
  `element_iframe` text COMMENT 'The iframe element represents a nested browsing context.',
  `element_embed` text COMMENT 'The embed element represents an integration point for an external (typically non-HTML) application or interactive content.',
  `element_object` text COMMENT 'The object element can represent an external resource, which, depending on the type of the resource, will either be treated as an image, as a nested browsing context, or as an external resource to be processed by a plugin.',
  `element_param` text COMMENT 'The param element defines parameters for plugins invoked by object elements. It does not represent anything on its own.',
  `element_video` text COMMENT 'A video element is used for playing videos or movies, and audio files with captions.',
  `element_audio` text COMMENT 'An audio element represents a sound or audio stream.',
  `element_source` text COMMENT 'The source element allows authors to specify multiple alternative media resources for media elements. It does not represent anything on its own.',
  `element_track` text COMMENT 'The track element allows authors to specify explicit external timed text tracks for media elements. It does not represent anything on its own.',
  `element_canvas` text COMMENT 'The canvas element provides scripts with a resolution-dependent bitmap canvas, which can be used for rendering graphs, game graphics, or other visual images on the fly.',
  `element_map` text COMMENT 'The map element, in conjunction with any area element descendants, defines an image map. The element represents its children.',
  `element_area` text COMMENT 'The area element represents either a hyperlink with some text and a corresponding area on an image map, or a dead area on an image map.',
  `element_table` text COMMENT 'The table element represents data with more than one dimension, in the form of a table.',
  `element_caption` text COMMENT 'The caption element represents the title of the table that is its parent, if it has a parent and that is a table element.',
  `element_colgroup` text COMMENT 'The colgroup element represents a group of one or more columns in the table that is its parent, if it has a parent and that is a table element.',
  `element_col` text COMMENT 'If a col element has a parent and that is a colgroup element that itself has a parent that is a table element, then the col element represents one or more columns in the column group represented by that colgroup.',
  `element_tbody` text COMMENT 'The tbody element represents a block of rows that consist of a body of data for the parent table element, if the tbody element has a parent and it is a table.',
  `element_thead` text COMMENT 'The thead element represents the block of rows that consist of the column labels (headers) for the parent table element, if the thead element has a parent and it is a table.',
  `element_tfoot` text COMMENT 'The tfoot element represents the block of rows that consist of the column summaries (footers) for the parent table element, if the tfoot element has a parent and it is a table.',
  `element_tr` text COMMENT 'The tr element represents a row of cells in a table.',
  `element_td` text COMMENT 'The td element represents a data cell in a table.',
  `element_th` text COMMENT 'The th element represents a header cell in a table.',
  `element_form` text COMMENT 'The form element represents a collection of form-associated elements, some of which can represent editable values that can be submitted to a server for processing.',
  `element_fieldset` text COMMENT 'The fieldset element represents a set of form controls optionally grouped under a common name.',
  `element_legend` text COMMENT 'The legend element represents a caption for the rest of the contents of the legend element''s parent fieldset element, if any.',
  `element_label` text COMMENT 'The label element represents a caption in a user interface. The caption can be associated with a specific form control, known as the label element''s labeled control, either using for attribute, or by putting the form control inside the label element itsel',
  `element_input` text COMMENT 'The input element represents a typed data field, usually with a form control to allow the user to edit the data.',
  `element_button` text COMMENT 'The button element represents a button. If the element is not disabled, then the user agent should allow the user to activate the button.',
  `element_select` text COMMENT 'The select element represents a control for selecting amongst a set of options.',
  `element_datalist` text COMMENT 'The datalist element represents a set of option elements that represent predefined options for other controls. The contents of the element represents fallback content for legacy user agents, intermixed with option elements that represent the predefined op',
  `element_optgroup` text COMMENT 'The optgroup element represents a group of option elements with a common label.',
  `element_option` text COMMENT 'The option element represents an option in a select element or as part of a list of suggestions in a datalist element.',
  `element_textarea` text COMMENT 'The textarea element represents a multiline plain text edit control for the element''s raw value. The contents of the control represent the control''s default value.',
  `element_keygen` text COMMENT 'The keygen element represents a key pair generator control. When the control''s form is submitted, the private key is stored in the local keystore, and the public key is packaged and sent to the server.',
  `element_output` text COMMENT 'The output element represents the result of a calculation.',
  `element_progress` text COMMENT 'The progress element represents the completion progress of a task. The progress is either indeterminate, indicating that progress is being made but that it is not clear how much more work remains to be done before the task is complete (e.g. because the ta',
  `element_meter` text COMMENT 'The meter element represents a scalar measurement within a known range, or a fractional value; for example disk usage, the relevance of a query result, or the fraction of a voting population to have selected a particular candidate.',
  `element_input_attribute_type_value_hidden` text COMMENT 'The input element represents a value that is not intended to be examined or manipulated by the user.',
  `element_input_attribute_type_value_text` text COMMENT 'The input element represents a one line plain text edit control for the element''s value.',
  `element_input_attribute_type_value_search` text COMMENT 'The input element represents a one line plain text edit control for the element''s value.',
  `element_input_attribute_type_value_telephone` text COMMENT 'The input element represents a control for editing a telephone number given in the element''s value.',
  `element_input_attribute_type_value_url` text COMMENT 'The input element represents a control for editing a single absolute URL given in the element''s value.',
  `element_input_attribute_type_value_email` text COMMENT 'The input element represents a control for editing an e-mail address given in the element''s value.',
  `element_input_attribute_type_value_password` text COMMENT 'The input element represents a one line plain text edit control for the element''s value. The user agent should obscure the value so that people other than the user cannot see it.',
  `element_input_attribute_type_value_date` text COMMENT 'The input element represents a control for setting the element''s value to a string representing a specific date.',
  `element_input_attribute_type_value_month` text COMMENT 'The input element represents a control for setting the element''s value to a string representing a specific month.',
  `element_input_attribute_type_value_week` text COMMENT 'The input element represents a control for setting the element''s value to a string representing a specific week.',
  `element_input_attribute_type_value_time` text COMMENT 'The input element represents a control for setting the element''s value to a string representing a specific time.',
  `element_input_attribute_type_value_datetimelocal` text COMMENT 'The input element represents a control for setting the element''s value to a string representing a local date and time, with no time-zone offset information.',
  `element_input_attribute_type_value_number` text COMMENT 'The input element represents a control for setting the element''s value to a string representing a number.',
  `element_input_attribute_type_value_range` text COMMENT 'The input element represents a control for setting the element''s value to a string representing a number, but with the caveat that the exact value is not important, letting UAs provide a simpler interface than they do for the Number state.',
  `element_input_attribute_type_value_color` text COMMENT 'The input element represents a color well control, for setting the element''s value to a string representing a simple color.',
  `element_input_attribute_type_value_checkbox` text COMMENT 'The input element represents a two-state control that represents the element''s checkedness state. If the element''s checkedness state is true, the control represents a positive selection, and if it is false, a negative selection. If the element''s indetermi',
  `element_input_attribute_type_value_radio` text COMMENT 'The input element represents a control that, when used in conjunction with other input elements, forms a radio button group in which only one control can have its checkedness state set to true. If the element''s checkedness state is true, the control repre',
  `element_input_attribute_type_value_file` text COMMENT 'The input element represents a list of selected files, each file consisting of a file name, a file type, and a file body (the contents of the file).',
  `element_input_attribute_type_value_submit` text COMMENT 'The input element represents a button that, when activated, submits the form. If the element has a value attribute, the button''s label must be the value of that attribute; otherwise, it must be an implementation-defined string that means "Submit" or some ',
  `element_input_attribute_type_value_image` text COMMENT 'The input element represents either an image from which a user can select a coordinate and submit the form, or alternatively a button from which the user can submit the form. The element is a button, specifically a submit button.',
  `element_input_attribute_type_value_reset` text COMMENT 'The input element represents a button that, when activated, resets the form. If the element has a value attribute, the button''s label must be the value of that attribute; otherwise, it must be an implementation-defined string that means "Reset" or some su',
  `element_input_attribute_type_value_button` text COMMENT 'The input element represents a button with no default behavior. A label for the button must be provided in the value attribute, though it may be the empty string. If the element has a value attribute, the button''s label must be the value of that attribute',
  `element_details` text COMMENT 'The details element represents a disclosure widget from which the user can obtain additional information or controls.',
  `element_summary` text COMMENT 'The summary element represents a summary, caption, or legend for the rest of the contents of the summary element''s parent details element, if any.',
  `element_command` text COMMENT 'The command element represents a command that the user can invoke.',
  `element_menu` text COMMENT 'The menu element represents a list of commands.',
  `pseudo_class_link` text COMMENT 'All a elements that have an href attribute, all area elements that have an href attribute, and all link elements that have an href attribute, must match one of :link and :visited.',
  `pseudo_class_visited` text COMMENT 'All a elements that have an href attribute, all area elements that have an href attribute, and all link elements that have an href attribute, must match one of :link and :visited.',
  `pseudo_class_active` text COMMENT 'The :active pseudo-class is defined to match an element while an element is being activated by the user.',
  `pseudo_class_enabled` text COMMENT 'The :enabled pseudo-class must match any element falling into one of the following categories: a elements that have an href attribute, area elements that have an href attribute, link elements that have an href attribute, button elements that are not disabled, input elements whose type attribute are not in the Hidden state and that are not disabled, select elements that are not disabled, textarea elements that are not disabled, optgroup elements that do not have a disabled attribute, option elements that are not disabled, command elements that do not have a disabled attribute, li elements that are children of menu elements, and that have a child element that defines a command, if the first such element''s Disabled State facet is false (not disabled), fieldset elements that do not have a disabled attribute.',
  `pseudo_class_disabled` text COMMENT 'The :disabled pseudo-class must match any element falling into one of the following categories: button elements that are disabled, input elements whose type attribute are not in the Hidden state and that are disabled, select elements that are disabled, textarea elements that are disabled, optgroup elements that have a disabled attribute, option elements that are disabled, command elements that have a disabled attribute, li elements that are children of menu elements, and that have a child element that defines a command, if the first such element''s Disabled State facet is true (disabled), fieldset elements that have a disabled attribute.',
  `pseudo_class_checked` text COMMENT 'The :checked pseudo-class must match any element falling into one of the following categories: input elements whose type attribute is in the Checkbox state and whose checkedness state is true, input elements whose type attribute is in the Radio Button state and whose checkedness state is true, option elements whose selectedness is true, command elements whose type attribute is in the Checkbox state and that have a checked attribute, command elements whose type attribute is in the Radio state and that have a checked attribute.',
  `pseudo_class_indeterminate` text COMMENT 'The :indeterminate pseudo-class must match any element falling into one of the following categories: input elements whose type attribute is in the Checkbox state and whose indeterminate IDL attribute is set to true, progress elements with no value content attribute.',
  `pseudo_class_default` text COMMENT 'The :default pseudo-class must match any element falling into one of the following categories: button elements that are their form''s default button, input elements whose type attribute is in the Submit Button or Image Button state, and that are their form''s default button, input elements to which the checked attribute applies and that have a checked attribute, option elements that have a selected attribute.',
  `pseudo_class_valid` text COMMENT 'The :valid pseudo-class must match all elements that are candidates for constraint validation and that satisfy their constraints.',
  `pseudo_class_invalid` text COMMENT 'The :invalid pseudo-class must match all elements that are candidates for constraint validation but that do not satisfy their constraints.',
  `pseudo_class_in_range` text COMMENT 'The :in-range pseudo-class must match all elements that are candidates for constraint validation, have range limitations, and that are neither suffering from an underflow nor suffering from an overflow.',
  `pseudo_class_out_of_range` text COMMENT 'The :out-of-range pseudo-class must match all elements that are candidates for constraint validation, have range limitations, and that are either suffering from an underflow or suffering from an overflow.',
  `pseudo_class_required` text COMMENT 'The :required pseudo-class must match any element falling into one of the following categories: input elements that are required, select elements that have a required attribute, textarea elements that have a required attribute.',
  `pseudo_class_optional` text COMMENT 'The :optional pseudo-class must match any element falling into one of the following categories: input elements to which the required attribute applies that are not required, select elements that do not have a required attribute, textarea elements that do not have a required attribute.',
  `pseudo_class_read_only` text COMMENT 'The :read-only pseudo-class must match all HTML elements other than those matched by the :read-write pseudo-class.',
  `pseudo_class_read_write` text COMMENT 'The :read-write pseudo-class must match any element falling into one of the following categories: input elements to which the readonly attribute applies, but that are not immutable (i.e. that do not have the readonly attribute specified and that are not disabled), textarea elements that do not have a readonly attribute, and that are not disabled, elements that are editing hosts or editable and are neither input elements nor textarea elements.',
  `pseudo_class_dir_ltr` text COMMENT 'The :dir(ltr) pseudo-class must match all elements whose directionality is ''ltr''.',
  `pseudo_class_dir_rtl` text COMMENT 'The :dir(rtl) pseudo-class must match all elements whose directionality is ''rtl''.',
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`),
  KEY `user` (`user_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

INSERT INTO `stylesheets` VALUES(1, 1, 'Default', 'The default stylesheet', '#fff', '#000', 13, 1.231, 'arial,helvetica,clean,sans-serif', 5, 950, 250, 300, 5, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'font-size:138.5%;font-weight:bold;margin:1em 0', 'font-size:123.1%;font-weight:bold;margin:1em 0', 'font-size:108%;font-weight:bold;margin:1em 0', 'font-weight:bold', 'font-weight:bold', 'font-weight:bold', NULL, NULL, NULL, NULL, 'margin-bottom:1em', NULL, 'margin-bottom:1em', 'margin:1em', 'list-style:decimal outside;margin:1em 1em 1em 2em', 'list-style:disc outside;margin:1em 1em 1em 2em', NULL, 'margin:1em', NULL, 'margin-left:1em', NULL, NULL, NULL, NULL, 'font-style:italic', 'font-weight:bold', NULL, NULL, NULL, NULL, NULL, 'border-bottom:1px dotted #000;cursor:help', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'font-style:italic', 'font-weight:bold', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'margin-bottom:1em', 'margin-bottom:.5em;text-align:center', NULL, NULL, NULL, NULL, NULL, NULL, 'border:1px solid #000;padding:.5em', 'border:1px solid #000;font-weight:bold;padding:.5em;text-align:center', NULL, 'margin-bottom:1em', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'width:12.25em;*width:11.9em', NULL, NULL, NULL, NULL, NULL, 'width:12.25em;*width:11.9em', NULL, NULL, NULL, NULL, 'width:12.25em;*width:11.9em', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2012-03-07 21:56:29', '2012-03-07 21:56:29');

DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) DEFAULT NULL,
  `email` varchar(100) NOT NULL,
  `password` char(40) NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`),
  KEY `password` (`password`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

INSERT INTO `users` VALUES(1, 'Robert Love', 'robert.love@signified.com.au', '46d45341e7e7fba77287d332833144e961fbbcb0', '2012-03-07 21:56:29', '2012-03-07 21:56:29');
